id: /subscriptions/e0783b50-4ca5-4059-83c1-524f39faa624/resourceGroups/rg-banking-new/providers/Microsoft.App/containerapps/account-mcp
identity:
  type: None
location: Sweden Central
name: account-mcp
properties:
  configuration:
    activeRevisionsMode: Single
    dapr: null
    identitySettings: []
    ingress:
      additionalPortMappings: null
      allowInsecure: false
      clientCertificateMode: null
      corsPolicy: null
      customDomains: null
      exposedPort: 0
      external: true
      fqdn: account-mcp.mangopond-a6402d9f.swedencentral.azurecontainerapps.io
      ipSecurityRestrictions: null
      stickySessions:
        affinity: none
      targetPort: 0
      traffic:
      - latestRevision: true
        weight: 100
      transport: Auto
    maxInactiveRevisions: 100
    registries:
    - identity: ''
      passwordSecretRef: reg-pswd-074ea5c7-ac29
      server: multimodaldemoacroy6neblxi3zkq.azurecr.io
      username: multimodaldemoacroy6neblxi3zkq
    runtime: null
    secrets:
    - name: reg-pswd-074ea5c7-ac29
    service: null
  customDomainVerificationId: B763D40B517987D4AEA45EB223B48B72CC661AD92FCC108DB8746583017346B0
  delegatedIdentities: []
  environmentId: /subscriptions/e0783b50-4ca5-4059-83c1-524f39faa624/resourceGroups/rg-a2a-test/providers/Microsoft.App/managedEnvironments/acae-a2a-test
  eventStreamEndpoint: https://swedencentral.azurecontainerapps.dev/subscriptions/e0783b50-4ca5-4059-83c1-524f39faa624/resourceGroups/rg-banking-new/containerApps/account-mcp/eventstream
  latestReadyRevisionName: account-mcp--0000002
  latestRevisionFqdn: account-mcp--0000002.mangopond-a6402d9f.swedencentral.azurecontainerapps.io
  latestRevisionName: account-mcp--0000002
  managedEnvironmentId: /subscriptions/e0783b50-4ca5-4059-83c1-524f39faa624/resourceGroups/rg-a2a-test/providers/Microsoft.App/managedEnvironments/acae-a2a-test
  outboundIpAddresses:
  - 20.240.28.167
  - 20.240.28.184
  - 9.223.20.105
  - 135.116.6.186
  - 9.223.21.30
  - 9.223.218.210
  - 135.116.14.134
  - 9.223.143.243
  - 9.223.9.149
  - 74.241.137.85
  - 74.241.139.161
  - 74.241.138.64
  - 20.240.28.187
  - 74.241.136.237
  - 9.223.21.119
  - 9.223.10.153
  - 9.223.225.145
  - 9.223.220.233
  - 74.241.136.44
  - 9.223.87.134
  - 74.241.139.29
  - 9.223.20.250
  - 9.223.20.145
  - 20.240.29.51
  - 74.241.193.90
  - 74.241.192.157
  - 74.241.192.45
  - 74.241.193.154
  - 74.241.192.111
  - 74.241.193.34
  - 20.240.38.142
  - 20.240.38.235
  - 9.223.237.26
  - 9.223.246.165
  - 74.241.209.91
  - 74.241.211.241
  - 9.223.245.238
  - 135.116.14.86
  - 9.223.173.128
  - 9.223.237.22
  - 4.225.86.27
  - 9.223.75.69
  - 20.240.37.255
  - 9.223.245.208
  - 9.223.237.31
  - 9.223.45.114
  - 9.223.24.231
  - 74.241.210.170
  - 9.223.246.185
  - 9.223.16.144
  - 135.116.37.178
  - 9.223.247.36
  - 9.223.18.163
  - 20.240.37.231
  - 74.241.204.139
  - 74.241.204.246
  - 74.241.202.17
  - 74.241.200.59
  - 74.241.205.78
  - 74.241.203.192
  - 9.223.13.183
  provisioningState: Succeeded
  runningStatus: Running
  template:
    containers:
    - image: multimodaldemoacroy6neblxi3zkq.azurecr.io/account-mcp:latest
      name: account-mcp
      probes: []
      resources:
        cpu: 0.5
        ephemeralStorage: 2Gi
        memory: 1Gi
      volumeMounts:
      - mountPath: /app/data
        volumeName: bankx-shared-data
      - mountPath: /app/memory
        volumeName: bankx-shared-data
    initContainers: null
    revisionSuffix: ''
    scale:
      cooldownPeriod: 300
      maxReplicas: 10
      minReplicas: 0
      pollingInterval: 30
      rules: null
    serviceBinds: null
    terminationGracePeriodSeconds: null
    volumes:
    - name: bankx-shared-data
      storageName: bankx-shared-data
      storageType: AzureFile
  workloadProfileName: Consumption
resourceGroup: rg-banking-new
systemData:
  createdAt: '2026-01-13T16:20:34.1903929'
  createdBy: Abhinav@metakaal.com
  createdByType: User
  lastModifiedAt: '2026-02-04T11:19:50.5079624'
  lastModifiedBy: Abhinav@metakaal.com
  lastModifiedByType: User
type: Microsoft.App/containerApps